version: "{build}"

image: Visual Studio 2017

artifacts:
  - path: "nuget\\*.nupkg"
    name: nuget
  - path: "UntisJson.Console\\bin\\Release\\gpo-to-json.exe"
    name: exe

install: 
  - nuget restore

build:
  project: UntisJson.sln

after_build:
  - cd nuget
  - nuget pack UntisJson.nuspec
  
configuration:
  - Release

platform:
  - Any CPU

deploy:
  - provider: NuGet
    api_key:
      secure: 4s5RMq4sJnnJ+qN8gxnovztWvDS6Ppsj6fO2XSl28utxsDTrBJbEGVp0M8LnRU+i
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      APPVEYOR_REPO_TAG: true

  - provider: GitHub
    release: $(appveyor_build_version)
    description: 'UntisJson Release'
    auth_token:
      secure: azxaxWtfK5LuSENJSnawf9JVCtyjlaPe9jXgjHt9Mt0gjl/IqTiKv26ZB034YQhc
    artifact: /.*\.(nupkg|exe)/
    on:
      APPVEYOR_REPO_TAG: true