version: "{build}"

image: Visual Studio 2017

artifacts:
  - path: "nuget\\*.nupkg"
    name: nuget
  - path: "UntisJson.Console\\bin\\Release\\gpo-to-json.exe"
    name: exe

install: 
  - nuget restore

build:
  project: UntisJson.sln

after_build:
  - cd nuget
  - nuget pack UntisJson.nuspec
  
configuration:
  - Release

platform:
  - Any CPU

deploy:
  - provider: NuGet
    api_key:
      secure: m/BZsZQssKrHAgtl+XEQ8j0mLr32jRvfar+4GgC39eRbXsOKWhvF+GEcuU53paNc
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      APPVEYOR_REPO_TAG: true

  - provider: GitHub
    release: $(appveyor_build_version)
    description: 'UntisJson Release'
    auth_token:
      secure: sMRP2nLdtaD7TmfOEHNrBYVQ030+IrC2APZmdguG45kvjLbvIJJYC8Y/ixsZw0VT
    artifact: /.*\.(nupkg|exe)/
    on:
      APPVEYOR_REPO_TAG: true